// Усі рядки інтерфейсу в одному місці (готово до i18n).
export const t = {
  brand: "STREETSTORE.13",
  nav: {
    home: "Головна",
    catalog: "Каталог",
    search: "Пошук",
    cart: "Кошик",
    profile: "Профіль",
  },
  common: {
    back: "Назад",
    retry: "Спробувати ще раз",
    all: "Усі",
    close: "Закрити",
    apply: "Показати",
    reset: "Скинути",
    loading: "Завантаження…",
  },
  errors: {
    network: "Немає з'єднання з магазином. Перевірте інтернет і спробуйте ще раз.",
    server: "Щось пішло не так на нашому боці. Спробуйте ще раз трохи пізніше.",
    generic: "Не вдалося завантажити дані.",
    notFoundTitle: "Сторінку не знайдено",
    productNotFound: "Товар не знайдено або він більше не продається.",
  },
  home: {
    searchPlaceholder: "Пошук товарів і брендів",
    newArrivals: "Новинки",
    popular: "Популярне",
    sale: "Акції",
    categories: "Категорії",
  },
  catalog: {
    title: "Каталог",
    allCategories: "Усе",
    filters: "Фільтри",
    sort: "Сортування",
    empty: "За цими фільтрами товарів немає",
    emptyHint: "Спробуйте прибрати частину фільтрів.",
    resetFilters: "Скинути фільтри",
    end: "Це всі товари",
    sorts: {
      new: "Спочатку нові",
      price_asc: "Спочатку дешевші",
      price_desc: "Спочатку дорожчі",
    },
  },
  filters: {
    brand: "Бренд",
    color: "Колір",
    size: "Розмір",
    price: "Ціна, ₴",
    priceFrom: "від",
    priceTo: "до",
    priceRangeError: "«Від» не може бути більшим за «до»",
    inStock: "Тільки в наявності",
    flags: "Добірки",
    isNew: "Новинки",
    isPopular: "Популярне",
    isSale: "Акції",
  },
  search: {
    placeholder: "Назва, бренд, категорія або артикул",
    hint: "Шукайте за назвою, брендом, категорією чи артикулом.",
    emptyTitle: (q: string) => `За запитом «${q}» нічого не знайдено`,
    emptyHint: "Перевірте написання або спробуйте коротший запит.",
    toCatalog: "Перейти в каталог",
    clear: "Очистити",
  },
  product: {
    sku: "Артикул",
    color: "Колір",
    size: "Розмір",
    quantity: "Кількість",
    chooseSize: "Оберіть розмір",
    chooseColor: "Оберіть колір",
    addToCart: "Додати в кошик",
    added: "Додано в кошик",
    outOfStock: "Немає в наявності",
    maxInCart: "У кошику вже максимальна кількість",
    lowStock: (n: number) => `Залишилось ${n} шт.`,
    unavailable: "немає",
    description: "Опис",
    material: "Матеріал",
    photo: (i: number, n: number) => `Фото ${i} з ${n}`,
  },
  badges: {
    new: "Новинка",
  },
  cart: {
    title: "Кошик",
    open: "Відкрити кошик",
    count: (n: number) => `Товарів у кошику: ${n}`,
    stage3: "Екран кошика й оформлення замовлення з'являться на наступному етапі.",
    empty: "Кошик порожній",
  },
  profile: {
    title: "Профіль",
    guest: "Гість",
    notInTelegram: "Відкрийте магазин у Telegram, щоб увійти.",
    loginFailed: "Не вдалося увійти через Telegram. Закрийте й відкрийте магазин ще раз.",
    stage3: "Мої замовлення з'являться на наступному етапі.",
    devMode: "Режим розробки: тестовий користувач",
  },
} as const;
